### ISSUE TITLE
Fixes for 2022/2023 data addition

### ISSUE THREAD

**Issue by alvizek** [SRJPE/jpe-deer-mill-edi#5]
Check with Ryan
- do we know what species "sm b" would be?
- 1 = sac fry, 2= fry, 3 = parr, 4 = silvery parr, 5 = smolt. We should confirm with Ryan.
- Release and recapture data for Deer?
- Release data for Mill? (we have recaptures)

After confirming lifestage and species need to update the lookup tables.

**Comment by ErinCain** [comment]
- "sm b" - smallmouth bass 
- life stage assumptions correct 
- Chanel scanning and sending release sheets
